version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: tarea
    environment:
      MYSQL_USER: main
      MYSQL_PASSWORD: algo
      MYSQL_ROOT_PASSWORD: algo
      MYSQL_DATABASE: springDB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

